### ISSUE TITLE
AttributeError: module 'sqlalchemy' has no attribute '__all__'

### ISSUE THREAD

**Issue by mikeki** [trotto/go-links#193] opened 2023-01-27 02:07 UTC
I can't figure out how to solve this issue, it was working fine until it wasn't.

```
2023-01-26 21:06:40   File "/usr/src/app/server/src/main.py", line 106, in <module>
2023-01-26 21:06:40     app = init_app_without_routes()
2023-01-26 21:06:40   File "/usr/src/app/server/src/main.py", line 54, in init_app_without_routes
2023-01-26 21:06:40     db = SQLAlchemy(app)
2023-01-26 21:06:40   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 720, in __init__
2023-01-26 21:06:40     _include_sqlalchemy(self, query_class)
2023-01-26 21:06:40   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 74, in _include_sqlalchemy
2023-01-26 21:06:40     for key in module.__all__:
2023-01-26 21:06:40 AttributeError: module 'sqlalchemy' has no attribute '__all__'
```

**Comment by carlozt03** [comment] 2023-01-27 17:19
I added `SQLAlchemy==1.2.19` to `requirements.txt` in the root folder and the /server/src folder and was able to build successfully.

**Comment by mikeki** [comment] 2023-01-27 17:40
Thank you! that fixed the issue. I'm super confused because I was able to run it without this missing dependency and then it didnt work

**Comment by itsojon** [comment] 2023-01-28 19:12
thank you for reporting @mikeki, and thank you for sharing the solution @carlozt03! this was caused by the release of SQLAlchemy 2.0.0 [a couple days ago](https://pypi.org/project/SQLAlchemy/#history) and SQLAlchemy only being included in Trotto as an indirect dependency, now fixed with https://github.com/trotto/go-links/pull/195.

**Closed by itsojon** 2023-01-28 19:12 UTC

**Comment by wanyama23** [comment] 2023-09-22 22:24
for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?

kindly please help
