### ISSUE TITLE
False positive on punycode -ed URL

### ISSUE THREAD

**Issue by kentoku24** [trotto/go-links#53] opened 2020-10-06 16:26 UTC
[](url)
<img width="794" alt="スクリーンショット 2020-10-07 1 18 55" src="https://user-images.githubusercontent.com/975196/95229387-7b520e80-083b-11eb-9de8-c3f0de87920a.png">

Legitimate URL such as https://xn--wmq0m700b.jp/h30 is considered to be invaild URL.

This happens because underlying library "validators (0.12.0)" does not recognize the URL above as "correct" URL.

solution:
Use the latest version of library such as validators 0.18.1

**Comment by itsojon** [comment] 2020-10-06 16:35
Duplicate of #54

**Closed by itsojon** 2020-10-06 16:35 UTC
